[2024-01-11T17:40:45.563+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:40:45.569+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:40:45.586+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:45.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:45.663+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:45.643+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:40:45.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:45.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.352 seconds
[2024-01-11T17:40:46.962+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:40:46.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:40:46.970+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:46.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:46.982+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:46.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:40:46.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:47.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.081 seconds
[2024-01-11T17:40:48.111+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:40:48.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:40:48.116+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:48.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:48.128+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:40:48.127+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:40:48.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:40:48.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.057 seconds
[2024-01-11T17:41:15.364+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:15.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:15.369+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:15.368+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:15.380+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:15.378+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:15.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:15.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.051 seconds
[2024-01-11T17:41:18.414+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:18.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:18.418+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:18.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:18.429+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:18.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:18.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:18.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.064 seconds
[2024-01-11T17:41:20.473+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:20.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:20.477+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:20.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:20.489+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:20.487+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:20.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:20.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.166 seconds
[2024-01-11T17:41:23.526+0000] {processor.py:161} INFO - Started process (PID=323) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:23.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:23.531+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:23.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:23.544+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:23.541+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:23.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:23.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.063 seconds
[2024-01-11T17:41:30.592+0000] {processor.py:161} INFO - Started process (PID=335) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:30.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:30.596+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:30.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:30.606+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:30.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:30.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:30.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:41:39.819+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:39.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:39.828+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:39.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:39.845+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:39.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:39.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:39.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.069 seconds
[2024-01-11T17:41:41.869+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:41.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:41.873+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:41.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:41.886+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:41.884+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:41.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:41.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.057 seconds
[2024-01-11T17:41:57.178+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:41:57.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:41:57.184+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:57.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:57.199+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:41:57.197+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:41:57.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:41:57.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.090 seconds
[2024-01-11T17:42:27.378+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:42:27.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:42:27.382+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:42:27.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:42:27.393+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:42:27.391+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:42:27.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:42:27.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.058 seconds
[2024-01-11T17:42:57.592+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:42:57.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:42:57.596+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:42:57.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:42:57.608+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:42:57.606+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:42:57.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:42:57.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.054 seconds
[2024-01-11T17:43:00.670+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:43:00.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:43:00.674+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:00.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:00.684+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:00.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 9
    default_args={
    ^
SyntaxError: invalid syntax
[2024-01-11T17:43:00.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:00.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.048 seconds
[2024-01-11T17:43:12.800+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:43:12.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:43:12.804+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:12.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:12.813+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:12.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 15
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:43:12.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:12.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.045 seconds
[2024-01-11T17:43:43.021+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:43:43.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:43:43.025+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:43.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:43.035+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:43.033+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 15
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:43:43.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:43.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.049 seconds
[2024-01-11T17:43:57.167+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:43:57.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:43:57.171+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:57.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:57.183+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:57.180+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 15
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:43:57.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:57.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.053 seconds
[2024-01-11T17:43:59.216+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:43:59.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:43:59.221+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:59.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:59.233+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:43:59.232+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 15
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:43:59.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:43:59.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.060 seconds
[2024-01-11T17:44:01.293+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:01.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:01.298+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:01.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:01.310+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:01.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:01.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:01.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.059 seconds
[2024-01-11T17:44:02.350+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:02.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:02.354+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:02.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:02.365+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:02.364+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:02.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:02.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.051 seconds
[2024-01-11T17:44:03.409+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:03.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:03.414+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:03.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:03.423+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:03.422+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
    ^
SyntaxError: invalid syntax
[2024-01-11T17:44:03.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:03.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.088 seconds
[2024-01-11T17:44:07.565+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:07.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:07.570+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:07.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:07.579+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:07.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:07.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:07.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.065 seconds
[2024-01-11T17:44:11.616+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:11.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:11.621+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:11.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:11.633+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:11.631+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:11.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:11.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.071 seconds
[2024-01-11T17:44:13.737+0000] {processor.py:161} INFO - Started process (PID=445) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:13.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:13.743+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:13.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:13.759+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:13.757+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:13.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:13.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.063 seconds
[2024-01-11T17:44:17.783+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:17.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:17.787+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:17.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:17.797+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:17.796+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:17.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:17.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.077 seconds
[2024-01-11T17:44:18.880+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:18.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:18.884+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:18.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:18.895+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:18.894+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:18.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:18.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:44:28.976+0000] {processor.py:161} INFO - Started process (PID=466) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:28.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:28.982+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:28.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:28.993+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:28.991+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 16
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:28.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:29.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:44:35.065+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:35.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:35.070+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:35.069+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:35.080+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:35.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:35.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:35.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:44:37.128+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:37.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:37.133+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:37.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:37.145+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:37.143+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    ) AS dag:
    ^
SyntaxError: invalid syntax
[2024-01-11T17:44:37.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:37.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:44:45.238+0000] {processor.py:161} INFO - Started process (PID=481) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:45.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:45.244+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:45.243+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:45.256+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:45.255+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:45.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:45.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.056 seconds
[2024-01-11T17:44:47.300+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:44:47.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:44:47.306+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:47.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:47.322+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:44:47.320+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:44:47.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:44:47.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.071 seconds
[2024-01-11T17:45:11.517+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:11.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:11.523+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:11.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:11.533+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:11.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    ) AS dag:
      ^
SyntaxError: invalid syntax
[2024-01-11T17:45:11.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:11.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.055 seconds
[2024-01-11T17:45:17.598+0000] {processor.py:161} INFO - Started process (PID=502) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:17.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:17.603+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:17.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:17.615+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:17.613+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 17
    )  dag:
       ^
SyntaxError: invalid syntax
[2024-01-11T17:45:17.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:17.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.090 seconds
[2024-01-11T17:45:18.689+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:18.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:18.693+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:18.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:18.706+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:18.705+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag '
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:18.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:18.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.055 seconds
[2024-01-11T17:45:30.811+0000] {processor.py:161} INFO - Started process (PID=518) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:30.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:30.815+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:30.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:30.826+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:30.823+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 12
    'reries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:30.829+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:30.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.053 seconds
[2024-01-11T17:45:44.927+0000] {processor.py:161} INFO - Started process (PID=523) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:44.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:44.932+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:44.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:44.943+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:44.941+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 7
    'reries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:44.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:44.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.051 seconds
[2024-01-11T17:45:48.036+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:48.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:48.040+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:48.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:48.050+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:48.049+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 8
    'reries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:48.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:48.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.051 seconds
[2024-01-11T17:45:55.099+0000] {processor.py:161} INFO - Started process (PID=533) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:55.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:55.107+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:55.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:55.128+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:55.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 7
    'reries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:55.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:55.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.091 seconds
[2024-01-11T17:45:56.166+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:45:56.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:45:56.170+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:56.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:56.181+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:45:56.179+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 13
    'reries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:45:56.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:45:56.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:46:01.272+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:46:01.273+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:46:01.275+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:01.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:01.286+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:01.284+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 13
    'retries_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:46:01.287+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:01.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:46:12.380+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:46:12.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:46:12.385+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:12.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:12.394+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:12.393+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 13
    'retries_delay':timedelta(minutes=2)},
    ^
SyntaxError: invalid syntax
[2024-01-11T17:46:12.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:12.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:46:38.614+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:46:38.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:46:38.619+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:38.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:38.630+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:38.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag '
    ^
SyntaxError: invalid syntax
[2024-01-11T17:46:38.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:38.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.054 seconds
[2024-01-11T17:46:51.691+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:46:51.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:46:51.696+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:51.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:51.705+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:51.704+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag'
    ^
SyntaxError: invalid syntax
[2024-01-11T17:46:51.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:51.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:46:54.786+0000] {processor.py:161} INFO - Started process (PID=575) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:46:54.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:46:54.790+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:54.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:54.799+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:46:54.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:46:54.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:46:54.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.045 seconds
[2024-01-11T17:47:11.915+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:11.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:11.920+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:11.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:11.930+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:11.929+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:11.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:11.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.051 seconds
[2024-01-11T17:47:13.979+0000] {processor.py:161} INFO - Started process (PID=591) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:13.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:13.983+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:13.982+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:13.995+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:13.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 23
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:13.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:14.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:47:17.075+0000] {processor.py:161} INFO - Started process (PID=596) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:17.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:17.083+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:17.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:17.101+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:17.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 23
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:17.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:17.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.078 seconds
[2024-01-11T17:47:20.098+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:20.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:20.103+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:20.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:20.112+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:20.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 23
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:20.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:20.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.049 seconds
[2024-01-11T17:47:22.125+0000] {processor.py:161} INFO - Started process (PID=606) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:22.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:22.130+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:22.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:22.141+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:22.139+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 5
    default_args={
    ^
IndentationError: unexpected indent
[2024-01-11T17:47:22.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:22.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.054 seconds
[2024-01-11T17:47:27.245+0000] {processor.py:161} INFO - Started process (PID=617) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:27.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:27.249+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:27.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:27.260+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:27.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 8
    'retries_delay':timedelta(minutes=2)}
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:27.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:27.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.048 seconds
[2024-01-11T17:47:29.280+0000] {processor.py:161} INFO - Started process (PID=622) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:29.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:29.284+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:29.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:29.294+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:29.292+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 5
    default_args={
    ^
IndentationError: unexpected indent
[2024-01-11T17:47:29.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:29.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:47:37.397+0000] {processor.py:161} INFO - Started process (PID=627) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:37.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:37.401+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:37.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:37.412+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:37.410+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 8
    'retries_delay':timedelta(minutes=2)}
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:37.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:37.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.053 seconds
[2024-01-11T17:47:49.486+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:47:49.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:47:49.491+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:49.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:49.502+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:47:49.500+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 8
    'retry_delay':timedelta(minutes=2)}
    ^
SyntaxError: invalid syntax
[2024-01-11T17:47:49.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:47:49.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.054 seconds
[2024-01-11T17:48:09.668+0000] {processor.py:161} INFO - Started process (PID=643) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:09.670+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:09.674+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:09.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:09.694+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:09.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 8
    'retry_delay':timedelta(minutes=2)
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:09.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:09.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.115 seconds
[2024-01-11T17:48:23.750+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:23.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:23.753+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:23.753+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:23.770+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:23.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:23.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:23.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.062 seconds
[2024-01-11T17:48:28.814+0000] {processor.py:161} INFO - Started process (PID=659) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:28.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:28.818+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:28.818+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:28.829+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:28.828+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 20
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:28.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:28.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.064 seconds
[2024-01-11T17:48:32.919+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:32.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:32.924+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:32.923+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:32.933+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:32.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:32.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:32.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.050 seconds
[2024-01-11T17:48:42.000+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:42.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:42.004+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:42.004+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:42.017+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:42.016+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:42.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:42.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.057 seconds
[2024-01-11T17:48:55.120+0000] {processor.py:161} INFO - Started process (PID=674) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:55.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:55.125+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:55.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:55.141+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:55.139+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:55.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:55.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.073 seconds
[2024-01-11T17:48:56.157+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:48:56.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:48:56.165+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:56.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:56.176+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:48:56.175+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:48:56.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:48:56.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.059 seconds
[2024-01-11T17:49:26.411+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:49:26.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:49:26.416+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:49:26.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:49:26.426+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:49:26.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:49:26.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:49:26.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.049 seconds
[2024-01-11T17:49:48.576+0000] {processor.py:161} INFO - Started process (PID=701) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:49:48.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:49:48.582+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:49:48.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:49:48.596+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:49:48.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:49:48.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:49:48.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.064 seconds
[2024-01-11T17:50:00.743+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:50:00.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:50:00.748+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:00.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:00.758+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:00.756+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:50:00.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:00.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.048 seconds
[2024-01-11T17:50:02.792+0000] {processor.py:161} INFO - Started process (PID=717) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:50:02.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:50:02.796+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:02.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:02.806+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:02.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:50:02.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:02.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.049 seconds
[2024-01-11T17:50:33.057+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:50:33.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:50:33.063+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:33.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:33.077+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:50:33.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:50:33.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:50:33.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.085 seconds
[2024-01-11T17:51:03.272+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:51:03.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:51:03.277+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:03.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:03.288+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:03.286+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 21
    bash_command='echo Hey Senyonjo we made it out first airflow dag',
    ^
SyntaxError: invalid syntax
[2024-01-11T17:51:03.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:03.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T17:51:15.556+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:51:15.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:51:15.563+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:15.562+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:15.718+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:16.471+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.470+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:BASH_DAG
[2024-01-11T17:51:16.490+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.490+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:BASH_DAG
[2024-01-11T17:51:16.503+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.503+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:BASH_DAG
[2024-01-11T17:51:16.506+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.505+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:51:16.554+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.554+0000] {dag.py:3055} INFO - Creating ORM DAG for BASH_DAG
[2024-01-11T17:51:16.616+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:16.616+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:51:16.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 1.110 seconds
[2024-01-11T17:51:46.790+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:51:46.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:51:46.798+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:46.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:46.833+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:51:46.882+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:46.882+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:51:46.930+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:51:46.930+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:51:46.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.188 seconds
[2024-01-11T17:52:17.126+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:52:17.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:52:17.131+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:17.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:52:17.160+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:52:17.201+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:17.200+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:52:17.241+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:17.240+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:52:17.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.164 seconds
[2024-01-11T17:52:47.388+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:52:47.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:52:47.392+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:47.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:52:47.437+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:52:47.485+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:47.485+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:52:47.588+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:52:47.588+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:52:47.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.279 seconds
[2024-01-11T17:53:18.314+0000] {processor.py:161} INFO - Started process (PID=788) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:53:18.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:53:18.319+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:18.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:53:18.352+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:53:18.404+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:18.403+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:53:18.451+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:18.450+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:53:18.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.180 seconds
[2024-01-11T17:53:48.695+0000] {processor.py:161} INFO - Started process (PID=799) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:53:48.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:53:48.700+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:48.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:53:48.725+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:53:48.765+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:48.764+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:53:48.807+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:53:48.806+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:53:48.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.146 seconds
[2024-01-11T17:54:18.922+0000] {processor.py:161} INFO - Started process (PID=810) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:54:18.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:54:18.926+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:18.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:18.953+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:18.997+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:18.997+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:54:19.038+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:19.038+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:54:19.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.156 seconds
[2024-01-11T17:54:26.102+0000] {processor.py:161} INFO - Started process (PID=815) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:54:26.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:54:26.109+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:26.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:26.152+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:26.232+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:26.232+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:54:26.400+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:26.399+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:54:26.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.729 seconds
[2024-01-11T17:54:57.079+0000] {processor.py:161} INFO - Started process (PID=832) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:54:57.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:54:57.087+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:57.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:57.128+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:54:57.180+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:57.179+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:54:57.227+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:54:57.227+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:54:57.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.209 seconds
[2024-01-11T17:55:27.504+0000] {processor.py:161} INFO - Started process (PID=843) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:55:27.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:55:27.510+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:27.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:55:27.539+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:55:27.583+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:27.583+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:55:27.624+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:27.624+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:55:27.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.166 seconds
[2024-01-11T17:55:57.753+0000] {processor.py:161} INFO - Started process (PID=848) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:55:57.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:55:57.759+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:57.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:55:57.785+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:55:57.825+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:57.824+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:55:57.867+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:55:57.866+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:55:57.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.155 seconds
[2024-01-11T17:56:28.099+0000] {processor.py:161} INFO - Started process (PID=865) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:56:28.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:56:28.105+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:28.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:56:28.142+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:56:28.190+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:28.189+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:56:28.231+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:28.231+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:56:28.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.166 seconds
[2024-01-11T17:56:58.318+0000] {processor.py:161} INFO - Started process (PID=876) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:56:58.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:56:58.323+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:58.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:56:58.348+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:56:58.390+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:58.389+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:56:58.429+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:56:58.429+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:56:58.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.151 seconds
[2024-01-11T17:57:28.769+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:57:28.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:57:28.781+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:28.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:57:28.808+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:57:28.949+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:28.949+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:57:29.026+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:29.026+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:57:29.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.388 seconds
[2024-01-11T17:57:59.260+0000] {processor.py:161} INFO - Started process (PID=897) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:57:59.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:57:59.264+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:59.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:57:59.293+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:57:59.338+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:59.338+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:57:59.380+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:57:59.380+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:57:59.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.164 seconds
[2024-01-11T17:58:29.618+0000] {processor.py:161} INFO - Started process (PID=908) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:58:29.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:58:29.622+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:29.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:58:29.648+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:58:29.689+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:29.689+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:58:29.733+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:29.733+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:58:29.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.149 seconds
[2024-01-11T17:58:59.832+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:58:59.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:58:59.841+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:59.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:58:59.877+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:58:59.919+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:59.919+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:58:59.992+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:58:59.992+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:59:00.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.759 seconds
[2024-01-11T17:59:30.831+0000] {processor.py:161} INFO - Started process (PID=930) to work on /opt/airflow/dags/mydag.py
[2024-01-11T17:59:30.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T17:59:30.836+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:59:30.836+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T17:59:30.873+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T17:59:30.928+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:59:30.928+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T17:59:30.993+0000] {logging_mixin.py:188} INFO - [2024-01-11T17:59:30.993+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T17:59:31.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.209 seconds
[2024-01-11T18:00:01.245+0000] {processor.py:161} INFO - Started process (PID=941) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:00:01.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:00:01.249+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:01.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:00:01.274+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:00:01.320+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:01.320+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:00:01.362+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:01.362+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:00:01.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.157 seconds
[2024-01-11T18:00:31.626+0000] {processor.py:161} INFO - Started process (PID=952) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:00:31.629+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:00:31.631+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:31.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:00:31.658+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:00:31.710+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:31.710+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:00:31.749+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:00:31.748+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:00:31.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.160 seconds
[2024-01-11T18:01:01.868+0000] {processor.py:161} INFO - Started process (PID=963) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:01:01.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:01:01.873+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:01.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:01.897+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:01.940+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:01.940+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:01:01.985+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:01.984+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:01:02.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.154 seconds
[2024-01-11T18:01:32.153+0000] {processor.py:161} INFO - Started process (PID=974) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:01:32.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:01:32.159+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:32.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:32.194+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:32.246+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:32.245+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:01:32.302+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:32.302+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:01:32.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.202 seconds
[2024-01-11T18:01:54.559+0000] {processor.py:161} INFO - Started process (PID=979) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:01:54.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:01:54.570+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:54.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:54.623+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:54.613+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task1 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:01:54.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:54.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.183 seconds
[2024-01-11T18:01:56.800+0000] {processor.py:161} INFO - Started process (PID=984) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:01:56.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:01:56.804+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:56.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:56.841+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:01:56.836+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:01:56.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:01:56.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.078 seconds
[2024-01-11T18:02:05.883+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:05.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:05.887+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:05.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:05.917+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:05.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:02:05.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:05.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.071 seconds
[2024-01-11T18:02:07.997+0000] {processor.py:161} INFO - Started process (PID=1000) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:07.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:08.001+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:08.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:08.012+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:08.011+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 29
    task1 >>
           ^
SyntaxError: invalid syntax
[2024-01-11T18:02:08.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:08.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.052 seconds
[2024-01-11T18:02:10.087+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:10.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:10.092+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:10.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:10.160+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:10.153+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:02:10.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:10.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.141 seconds
[2024-01-11T18:02:12.136+0000] {processor.py:161} INFO - Started process (PID=1010) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:12.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:12.140+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:12.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:12.179+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:12.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:02:12.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:12.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.082 seconds
[2024-01-11T18:02:16.284+0000] {processor.py:161} INFO - Started process (PID=1015) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:16.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:16.288+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:16.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:16.320+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:16.317+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:02:16.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:16.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.108 seconds
[2024-01-11T18:02:46.528+0000] {processor.py:161} INFO - Started process (PID=1026) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:02:46.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:02:46.533+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:46.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:46.563+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:02:46.559+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:02:46.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:02:46.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.077 seconds
[2024-01-11T18:03:16.805+0000] {processor.py:161} INFO - Started process (PID=1037) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:03:16.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:03:16.809+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:16.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:16.830+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:16.827+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mydag.py", line 24, in <module>
    task2 = BashOperator (
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 816, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'first_dag' has already been added to the DAG
[2024-01-11T18:03:16.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:16.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.061 seconds
[2024-01-11T18:03:29.983+0000] {processor.py:161} INFO - Started process (PID=1048) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:03:29.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:03:29.989+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:29.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:30.025+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:30.206+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:30.206+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:03:30.242+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:30.242+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:03:30.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.303 seconds
[2024-01-11T18:03:31.048+0000] {processor.py:161} INFO - Started process (PID=1053) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:03:31.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:03:31.066+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:31.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:31.151+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:03:31.187+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:31.187+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:03:31.242+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:03:31.242+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:03:31.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.251 seconds
[2024-01-11T18:04:01.494+0000] {processor.py:161} INFO - Started process (PID=1064) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:04:01.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:04:01.498+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:01.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:04:01.527+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:04:01.727+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:01.727+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:04:01.764+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:01.764+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:04:01.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.309 seconds
[2024-01-11T18:04:32.018+0000] {processor.py:161} INFO - Started process (PID=1075) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:04:32.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:04:32.022+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:32.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:04:32.048+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:04:32.089+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:32.088+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:04:32.126+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:04:32.126+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:04:32.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.145 seconds
[2024-01-11T18:05:02.217+0000] {processor.py:161} INFO - Started process (PID=1086) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:05:02.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:05:02.224+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:02.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:05:02.272+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:05:02.319+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:02.319+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:05:02.379+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:02.379+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:05:02.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.222 seconds
[2024-01-11T18:05:32.544+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:05:32.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:05:32.549+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:32.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:05:32.574+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:05:32.617+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:32.616+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:05:32.655+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:05:32.654+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:05:32.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.148 seconds
[2024-01-11T18:06:02.892+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:06:02.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:06:02.896+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:02.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:06:02.920+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:06:02.959+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:02.959+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:06:03.002+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:03.002+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:06:03.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.144 seconds
[2024-01-11T18:06:33.100+0000] {processor.py:161} INFO - Started process (PID=1118) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:06:33.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:06:33.105+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:33.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:06:33.130+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:06:33.171+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:33.170+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:06:33.209+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:06:33.208+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:06:33.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.143 seconds
[2024-01-11T18:07:04.037+0000] {processor.py:161} INFO - Started process (PID=1129) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:07:04.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:07:04.042+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:04.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:07:04.075+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:07:04.130+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:04.129+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:07:04.185+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:04.184+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:07:04.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.189 seconds
[2024-01-11T18:07:34.303+0000] {processor.py:161} INFO - Started process (PID=1140) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:07:34.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:07:34.308+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:34.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:07:34.335+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:07:34.376+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:34.375+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:07:34.414+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:07:34.414+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:07:34.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.148 seconds
[2024-01-11T18:08:04.508+0000] {processor.py:161} INFO - Started process (PID=1151) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:08:04.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:08:04.513+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:04.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:08:04.540+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:08:04.581+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:04.580+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:08:04.620+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:04.620+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:08:04.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.159 seconds
[2024-01-11T18:08:34.837+0000] {processor.py:161} INFO - Started process (PID=1162) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:08:34.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:08:34.843+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:34.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:08:34.869+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:08:34.909+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:34.909+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:08:34.948+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:08:34.947+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:08:34.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.144 seconds
[2024-01-11T18:09:05.031+0000] {processor.py:161} INFO - Started process (PID=1173) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:09:05.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:09:05.036+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:05.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:09:05.060+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:09:05.102+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:05.102+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:09:05.141+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:05.141+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:09:05.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.148 seconds
[2024-01-11T18:09:35.354+0000] {processor.py:161} INFO - Started process (PID=1185) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:09:35.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:09:35.358+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:35.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:09:35.435+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:09:35.474+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:35.474+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:09:35.511+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:09:35.511+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:09:35.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.191 seconds
[2024-01-11T18:10:05.766+0000] {processor.py:161} INFO - Started process (PID=1196) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:10:05.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:10:05.777+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:05.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:10:05.801+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:10:05.840+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:05.840+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:10:05.878+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:05.877+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:10:05.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.150 seconds
[2024-01-11T18:10:35.968+0000] {processor.py:161} INFO - Started process (PID=1207) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:10:35.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:10:35.976+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:35.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:10:36.012+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:10:36.131+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:36.130+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:10:36.207+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:10:36.207+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:10:36.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.328 seconds
[2024-01-11T18:11:06.466+0000] {processor.py:161} INFO - Started process (PID=1218) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:11:06.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:11:06.470+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:06.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:11:06.493+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:11:06.534+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:06.533+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:11:06.578+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:06.578+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:11:06.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.146 seconds
[2024-01-11T18:11:36.684+0000] {processor.py:161} INFO - Started process (PID=1229) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:11:36.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:11:36.689+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:36.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:11:36.718+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:11:36.773+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:36.773+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:11:36.825+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:11:36.824+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:11:36.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.193 seconds
[2024-01-11T18:12:07.022+0000] {processor.py:161} INFO - Started process (PID=1240) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:12:07.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:12:07.026+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:07.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:12:07.054+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:12:07.107+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:07.107+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:12:07.155+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:07.155+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:12:07.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.170 seconds
[2024-01-11T18:12:37.297+0000] {processor.py:161} INFO - Started process (PID=1251) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:12:37.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:12:37.302+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:37.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:12:37.329+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:12:37.375+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:37.374+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:12:37.417+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:12:37.417+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:12:37.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.160 seconds
[2024-01-11T18:13:07.594+0000] {processor.py:161} INFO - Started process (PID=1262) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:13:07.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:13:07.601+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:07.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:13:07.711+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:13:07.792+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:07.792+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:13:07.837+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:07.837+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:13:07.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.283 seconds
[2024-01-11T18:13:38.095+0000] {processor.py:161} INFO - Started process (PID=1273) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:13:38.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:13:38.103+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:38.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:13:38.152+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:13:38.208+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:38.208+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:13:38.276+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:13:38.275+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:13:38.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.229 seconds
[2024-01-11T18:14:08.555+0000] {processor.py:161} INFO - Started process (PID=1284) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:14:08.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:14:08.562+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:08.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:14:08.604+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:14:08.671+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:08.670+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:14:08.726+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:08.726+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:14:08.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.213 seconds
[2024-01-11T18:14:38.996+0000] {processor.py:161} INFO - Started process (PID=1295) to work on /opt/airflow/dags/mydag.py
[2024-01-11T18:14:38.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mydag.py for tasks to queue
[2024-01-11T18:14:39.001+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:39.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mydag.py
[2024-01-11T18:14:39.029+0000] {processor.py:840} INFO - DAG(s) 'BASH_DAG' retrieved from /opt/airflow/dags/mydag.py
[2024-01-11T18:14:39.088+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:39.088+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-11T18:14:39.138+0000] {logging_mixin.py:188} INFO - [2024-01-11T18:14:39.137+0000] {dag.py:3820} INFO - Setting next_dagrun for BASH_DAG to 2024-01-12T00:00:00+00:00, run_after=2024-01-13T00:00:00+00:00
[2024-01-11T18:14:39.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mydag.py took 0.185 seconds
